// site/src/components/NavBar.tsx
import { useState } from "react"
import { Menu, X, Github } from "lucide-react"
import { ScrollProgress } from "@/components/ui/scroll-progress"
import { Logo } from "@/components/Logo"

const navLinks = [
  { label: "Features", href: "#features" },
  { label: "Showcase", href: "#showcase" },
  { label: "FAQ", href: "#faq" },
  {
    label: "Docs",
    href: "https://sub-frame.dev/docs/",
    external: true,
  },
  {
    label: "Blog",
    href: "https://sub-frame.dev/blog/",
    external: true,
  },
  {
    label: "GitHub",
    href: "https://github.com/Codename-11/SubFrame",
    external: true,
    icon: true,
  },
] as { label: string; href: string; external?: boolean; icon?: boolean }[]

export function NavBar() {
  const [mobileOpen, setMobileOpen] = useState(false)

  return (
    <>
      <ScrollProgress className="z-[60]" />
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-bg-deep/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-[1200px] items-center justify-between px-6 py-2">
          {/* Logo + version */}
          <a href="#" className="flex items-center gap-2 no-underline">
            <Logo size={54} id="nv" frame={false} animate={true} />
            <div className="flex flex-col leading-none">
              <span className="text-base font-bold text-text-primary">
                SubFrame
              </span>
              <span className="text-[10px] font-mono">
                <span className="text-emerald-400">Latest:</span>{" "}
                <span className="text-amber-400">v{__APP_VERSION__}</span>
              </span>
            </div>
          </a>

          {/* Desktop nav */}
          <div className="hidden items-center gap-6 md:flex">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                target={link.external ? "_blank" : undefined}
                rel={link.external ? "noopener noreferrer" : undefined}
                className="text-sm text-text-secondary transition-colors hover:text-text-primary no-underline inline-flex items-center gap-1"
              >
                {"icon" in link && link.icon && <Github size={15} />}
                {link.label}
              </a>
            ))}
            <a
              href="#download"
              className="rounded-lg bg-white px-4 py-1.5 text-sm font-semibold text-black transition-colors hover:bg-white/90 no-underline"
            >
              Download
            </a>
          </div>

          {/* Mobile menu button */}
          <button
            className="text-text-secondary md:hidden"
            onClick={() => setMobileOpen(!mobileOpen)}
            aria-label="Toggle menu"
          >
            {mobileOpen ? <X size={20} /> : <Menu size={20} />}
          </button>
        </div>

        {/* Mobile nav */}
        {mobileOpen && (
          <div className="border-t border-white/5 bg-bg-deep/95 px-6 pb-4 pt-2 backdrop-blur-xl md:hidden">
            {navLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                target={link.external ? "_blank" : undefined}
                rel={link.external ? "noopener noreferrer" : undefined}
                className="block py-2 text-sm text-text-secondary transition-colors hover:text-text-primary no-underline"
                onClick={() => setMobileOpen(false)}
              >
                {link.label}
              </a>
            ))}
            <a
              href="#download"
              className="mt-2 block w-full rounded-lg bg-white px-4 py-1.5 text-center text-sm font-semibold text-black transition-colors hover:bg-white/90 no-underline"
              onClick={() => setMobileOpen(false)}
            >
              Download
            </a>
          </div>
        )}
      </nav>
    </>
  )
}

// docs/.vitepress/theme/components/NavBar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { withBase } from 'vitepress'
import LogoSvg from './LogoSvg.vue'

const mobileMenuOpen = ref(false)

function onAnchorClick(e: Event, href: string) {
  e.preventDefault()
  // If we're on the homepage, scroll to section
  const el = document.querySelector(href)
  if (el) {
    el.scrollIntoView({ behavior: 'smooth' })
  } else {
    // Navigate to homepage with hash
    window.location.href = withBase('/') + href
  }
}

function onMobileNav(e: Event, href: string) {
  mobileMenuOpen.value = false
  onAnchorClick(e, href)
}
</script>

<template>
  <nav class="sf-nav" aria-label="Main navigation">
    <div class="container">
      <a :href="withBase('/')" class="logo">
        <div class="logo-icon">
          <LogoSvg :size="54" id="nv" :frame="true" />
        </div>
        <div class="logo-label">
          <span class="logo-text">SubFrame</span>
          <span class="logo-version">Latest: v0.1.0-beta.4</span>
        </div>
      </a>

      <div class="nav-links">
        <a href="#features" @click="onAnchorClick($event, '#features')">Features</a>
        <a href="#showcase" @click="onAnchorClick($event, '#showcase')">Showcase</a>
        <a href="#faq" @click="onAnchorClick($event, '#faq')">FAQ</a>
        <a :href="withBase('/guide/')">Docs</a>
        <a :href="withBase('/blog/')">Blog</a>
        <a href="https://github.com/Codename-11/SubFrame" target="_blank" rel="noopener noreferrer">GitHub</a>
      </div>

      <div class="nav-cta">
        <a href="https://github.com/Codename-11/SubFrame" class="btn btn-ghost" target="_blank" rel="noopener noreferrer">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
          </svg>
          GitHub
        </a>
        <a href="#download" class="btn btn-primary" @click="onAnchorClick($event, '#download')">Download</a>
      </div>

      <button class="nav-hamburger" :class="{ open: mobileMenuOpen }" @click="mobileMenuOpen = !mobileMenuOpen" aria-label="Toggle navigation menu" :aria-expanded="mobileMenuOpen.toString()">
        <span></span>
        <span></span>
        <span></span>
      </button>

      <div class="nav-mobile-menu" :class="{ open: mobileMenuOpen }">
        <a href="#features" @click="onMobileNav($event, '#features')">Features</a>
        <a href="#showcase" @click="onMobileNav($event, '#showcase')">Showcase</a>
        <a href="#faq" @click="onMobileNav($event, '#faq')">FAQ</a>
        <a :href="withBase('/guide/')">Docs</a>
        <a :href="withBase('/blog/')">Blog</a>
        <a href="https://github.com/Codename-11/SubFrame" target="_blank" rel="noopener noreferrer">GitHub</a>
        <a href="#download" @click="onMobileNav($event, '#download')">Download</a>
      </div>
    </div>
  </nav>
</template>
